In [23]:
import os
import pandas as pd

caminho = os.path.join("..", "data", 'housing.csv')

housing = pd.read_csv(caminho, sep=r"\s+", engine="python")
housing.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [24]:
import numpy as np

housing["CRIM"] = housing["CRIM"] * 100
housing["NOX"] = housing["NOX"] * 10

housing = np.round(housing, 0)
housing.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,1.0,18.0,2.0,0,5.0,7.0,65.0,4.0,1,296.0,15.0,397.0,5.0,24.0
1,3.0,0.0,7.0,0,5.0,6.0,79.0,5.0,2,242.0,18.0,397.0,9.0,22.0
2,3.0,0.0,7.0,0,5.0,7.0,61.0,5.0,2,242.0,18.0,393.0,4.0,35.0
3,3.0,0.0,2.0,0,5.0,7.0,46.0,6.0,3,222.0,19.0,395.0,3.0,33.0
4,7.0,0.0,2.0,0,5.0,7.0,54.0,6.0,3,222.0,19.0,397.0,5.0,36.0

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Separação dos dados
input = housing.drop(columns='MEDV')
output = housing['MEDV']

input_train, input_test, output_train, output_test = train_test_split(input, output, test_size = 0.2, random_state=42)

#Instanciar randomforest
rf_model = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42)

#Treinando o Algoritimo
rf_model.fit(input_train, output_train)

rf_predict = rf_model.predict(input_test)

print("Acurácia:", accuracy_score(output_test, rf_predict))
print("Matriz de confusão:\n", confusion_matrix(output_test, rf_predict))
print("Relatório de classificação:\n", classification_report(output_test, rf_predict))

Acurácia: 0.16666666666666666
Matriz de confusão:
 [[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
Relatório de classificação:
               precision    recall  f1-score   support

         5.0       0.00      0.00      0.00         1
         7.0       0.33      0.50      0.40         2
         8.0       0.00      0.00      0.00         0
        10.0       0.00      0.00      0.00         4
        11.0       0.00      0.00      0.00         2
        12.0       0.00      0.00      0.00         0
        13.0       0.11      0.25      0.15         4
        14.0       0.00      0.00      0.00         5
        15.0       0.00      0.00      0.00         4
        16.0       0.00      0.00      0.00         2
        17.0       0.00      0.00      0.00         6
        18.0       0.14      0.17      0.15         6
        19.0       0.00      0.00      0.00         6
        20.0       0.60      0.27      0.38        11
        21.0       0.33      0.12      0.18         8
        22.0       0.17      0.75      0.27         4
        23.0       0.08      0.17      0.11         6
        24.0       0.50      0.12      0.20         8
        25.0       0.50      0.20      0.29         5
        26.0       0.00      0.00      0.00         1
        27.0       0.00      0.00      0.00         0
        28.0       0.33      0.33      0.33         3
        29.0       0.00      0.00      0.00         2
        30.0       0.00      0.00      0.00         1
        31.0       0.00      0.00      0.00         1
        32.0       0.33      0.50      0.40         2
        33.0       0.00      0.00      0.00         0
        35.0       0.33      0.33      0.33         3
        42.0       0.00      0.00      0.00         0
        44.0       0.00      0.00      0.00         1
        48.0       0.00      0.00      0.00         1
        50.0       0.50      0.33      0.40         3

    accuracy                           0.17       102
   macro avg       0.13      0.13      0.11       102
weighted avg       0.23      0.17      0.16       102

c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Separação dos dados
cols = ['MEDV', 'CRIM', 'NOX']
input = housing.drop(columns= cols)
output = housing['MEDV']

input_train, input_test, output_train, output_test = train_test_split(input, output, test_size = 0.2, random_state=42)

#Instanciar randomforest
rf_model = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42)

#Treinando o Algoritimo
rf_model.fit(input_train, output_train)

rf_predict = rf_model.predict(input_test)

print("Acurácia:", accuracy_score(output_test, rf_predict))
print("Matriz de confusão:\n", confusion_matrix(output_test, rf_predict))
print("Relatório de classificação:\n", classification_report(output_test, rf_predict))

Acurácia: 0.13725490196078433
Matriz de confusão:
 [[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
Relatório de classificação:
               precision    recall  f1-score   support

         5.0       0.00      0.00      0.00         1
         7.0       0.33      0.50      0.40         2
         8.0       0.00      0.00      0.00         0
         9.0       0.00      0.00      0.00         0
        10.0       0.00      0.00      0.00         4
        11.0       0.00      0.00      0.00         2
        12.0       0.00      0.00      0.00         0
        13.0       0.12      0.25      0.17         4
        14.0       0.00      0.00      0.00         5
        15.0       0.00      0.00      0.00         4
        16.0       0.00      0.00      0.00         2
        17.0       0.00      0.00      0.00         6
        18.0       0.14      0.17      0.15         6
        19.0       0.14      0.17      0.15         6
        20.0       0.40      0.18      0.25        11
        21.0       0.17      0.12      0.14         8
        22.0       0.09      0.25      0.13         4
        23.0       0.10      0.17      0.12         6
        24.0       0.25      0.12      0.17         8
        25.0       0.20      0.20      0.20         5
        26.0       0.00      0.00      0.00         1
        28.0       0.00      0.00      0.00         3
        29.0       0.00      0.00      0.00         2
        30.0       0.00      0.00      0.00         1
        31.0       0.00      0.00      0.00         1
        32.0       0.00      0.00      0.00         2
        33.0       0.00      0.00      0.00         0
        35.0       0.40      0.67      0.50         3
        37.0       0.00      0.00      0.00         0
        44.0       0.00      0.00      0.00         1
        47.0       0.00      0.00      0.00         0
        48.0       0.00      0.00      0.00         1
        50.0       1.00      0.33      0.50         3

    accuracy                           0.14       102
   macro avg       0.10      0.09      0.09       102
weighted avg       0.16      0.14      0.14       102

c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [33]:
from sklearn.preprocessing import StandardScaler

#Separação dos dados
input = housing.drop(columns='MEDV')
output = housing['MEDV']
input_train, input_test, output_train, output_test = train_test_split(input, output, test_size = 0.2, random_state=42)

#Instanciar randomforest
rf_model = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42)

#Escalonando os dados
scaler = StandardScaler()
input_train_scaled = scaler.fit_transform(input_train)

input_test_scaled = scaler.transform(input_test)

#Treinando o Algoritimo
rf_model.fit(input_train_scaled, output_train)

rf_predict = rf_model.predict(input_test_scaled)

print("Acurácia:", accuracy_score(output_test, rf_predict))
print("Matriz de confusão:\n", confusion_matrix(output_test, rf_predict))
print("Relatório de classificação:\n", classification_report(output_test, rf_predict))

Acurácia: 0.1568627450980392
Matriz de confusão:
 [[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
Relatório de classificação:
               precision    recall  f1-score   support

         5.0       0.00      0.00      0.00         1
         7.0       0.33      0.50      0.40         2
         8.0       0.00      0.00      0.00         0
        10.0       0.00      0.00      0.00         4
        11.0       0.00      0.00      0.00         2
        12.0       0.00      0.00      0.00         0
        13.0       0.11      0.25      0.15         4
        14.0       0.00      0.00      0.00         5
        15.0       0.00      0.00      0.00         4
        16.0       0.00      0.00      0.00         2
        17.0       0.00      0.00      0.00         6
        18.0       0.14      0.17      0.15         6
        19.0       0.00      0.00      0.00         6
        20.0       0.60      0.27      0.38        11
        21.0       0.33      0.12      0.18         8
        22.0       0.17      0.75      0.27         4
        23.0       0.08      0.17      0.11         6
        24.0       0.50      0.12      0.20         8
        25.0       0.50      0.20      0.29         5
        26.0       0.00      0.00      0.00         1
        27.0       0.00      0.00      0.00         0
        28.0       0.33      0.33      0.33         3
        29.0       0.00      0.00      0.00         2
        30.0       0.00      0.00      0.00         1
        31.0       0.00      0.00      0.00         1
        32.0       0.33      0.50      0.40         2
        33.0       0.00      0.00      0.00         0
        35.0       0.00      0.00      0.00         3
        42.0       0.00      0.00      0.00         0
        44.0       0.00      0.00      0.00         1
        48.0       0.00      0.00      0.00         1
        50.0       0.50      0.33      0.40         3

    accuracy                           0.16       102
   macro avg       0.12      0.12      0.10       102
weighted avg       0.22      0.16      0.15       102

c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [34]:
from sklearn.preprocessing import StandardScaler

#Separação dos dados
cols = ['MEDV', 'CRIM', 'NOX']
input = housing.drop(columns= cols)
output = housing['MEDV']
input_train, input_test, output_train, output_test = train_test_split(input, output, test_size = 0.2, random_state=42)

#Instanciar randomforest
rf_model = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42)

#Escalonando os dados
scaler = StandardScaler()
input_train_scaled = scaler.fit_transform(input_train)

input_test_scaled = scaler.transform(input_test)

#Treinando o Algoritimo
rf_model.fit(input_train_scaled, output_train)

rf_predict = rf_model.predict(input_test_scaled)

print("Acurácia:", accuracy_score(output_test, rf_predict))
print("Matriz de confusão:\n", confusion_matrix(output_test, rf_predict))
print("Relatório de classificação:\n", classification_report(output_test, rf_predict))

Acurácia: 0.12745098039215685
Matriz de confusão:
 [[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
Relatório de classificação:
               precision    recall  f1-score   support

         5.0       0.00      0.00      0.00         1
         7.0       0.33      0.50      0.40         2
         8.0       0.00      0.00      0.00         0
         9.0       0.00      0.00      0.00         0
        10.0       0.00      0.00      0.00         4
        11.0       0.00      0.00      0.00         2
        12.0       0.00      0.00      0.00         0
        13.0       0.12      0.25      0.17         4
        14.0       0.00      0.00      0.00         5
        15.0       0.00      0.00      0.00         4
        16.0       0.00      0.00      0.00         2
        17.0       0.00      0.00      0.00         6
        18.0       0.12      0.17      0.14         6
        19.0       0.14      0.17      0.15         6
        20.0       0.40      0.18      0.25        11
        21.0       0.17      0.12      0.14         8
        22.0       0.08      0.25      0.12         4
        23.0       0.10      0.17      0.12         6
        24.0       0.00      0.00      0.00         8
        25.0       0.17      0.20      0.18         5
        26.0       0.00      0.00      0.00         1
        28.0       0.00      0.00      0.00         3
        29.0       0.00      0.00      0.00         2
        30.0       0.00      0.00      0.00         1
        31.0       0.00      0.00      0.00         1
        32.0       0.00      0.00      0.00         2
        33.0       0.00      0.00      0.00         0
        35.0       0.40      0.67      0.50         3
        37.0       0.00      0.00      0.00         0
        44.0       0.00      0.00      0.00         1
        47.0       0.00      0.00      0.00         0
        48.0       0.00      0.00      0.00         1
        50.0       1.00      0.33      0.50         3

    accuracy                           0.13       102
   macro avg       0.09      0.09      0.08       102
weighted avg       0.14      0.13      0.12       102

c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [35]:
from sklearn.preprocessing import MinMaxScaler

#Separação dos dados
input = housing.drop(columns='MEDV')
output = housing['MEDV']
input_train, input_test, output_train, output_test = train_test_split(input, output, test_size = 0.2, random_state=42)

#Instanciar randomforest
rf_model = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42)

#Escalonando os dados
scaler = MinMaxScaler()
input_train_scaled = scaler.fit_transform(input_train)

input_test_scaled = scaler.transform(input_test)

#Treinando o Algoritimo
rf_model.fit(input_train_scaled, output_train)

rf_predict = rf_model.predict(input_test_scaled)

print("Acurácia:", accuracy_score(output_test, rf_predict))
print("Matriz de confusão:\n", confusion_matrix(output_test, rf_predict))
print("Relatório de classificação:\n", classification_report(output_test, rf_predict))

Acurácia: 0.1568627450980392
Matriz de confusão:
 [[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
Relatório de classificação:
               precision    recall  f1-score   support

         5.0       0.00      0.00      0.00         1
         7.0       0.33      0.50      0.40         2
         8.0       0.00      0.00      0.00         0
        10.0       0.00      0.00      0.00         4
        11.0       0.00      0.00      0.00         2
        12.0       0.00      0.00      0.00         0
        13.0       0.11      0.25      0.15         4
        14.0       0.00      0.00      0.00         5
        15.0       0.00      0.00      0.00         4
        16.0       0.00      0.00      0.00         2
        17.0       0.00      0.00      0.00         6
        18.0       0.14      0.17      0.15         6
        19.0       0.00      0.00      0.00         6
        20.0       0.60      0.27      0.38        11
        21.0       0.25      0.12      0.17         8
        22.0       0.12      0.50      0.19         4
        23.0       0.08      0.17      0.11         6
        24.0       0.50      0.12      0.20         8
        25.0       0.33      0.20      0.25         5
        26.0       0.00      0.00      0.00         1
        27.0       0.00      0.00      0.00         0
        28.0       0.33      0.33      0.33         3
        29.0       0.00      0.00      0.00         2
        30.0       0.00      0.00      0.00         1
        31.0       0.00      0.00      0.00         1
        32.0       0.50      0.50      0.50         2
        33.0       0.00      0.00      0.00         0
        35.0       0.33      0.33      0.33         3
        42.0       0.00      0.00      0.00         0
        44.0       0.00      0.00      0.00         1
        48.0       0.00      0.00      0.00         1
        50.0       0.50      0.33      0.40         3

    accuracy                           0.16       102
   macro avg       0.13      0.12      0.11       102
weighted avg       0.21      0.16      0.16       102

c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [36]:
from sklearn.preprocessing import MinMaxScaler

#Separação dos dados
cols = ['MEDV', 'CRIM', 'NOX']
input = housing.drop(columns= cols)
output = housing['MEDV']
input_train, input_test, output_train, output_test = train_test_split(input, output, test_size = 0.2, random_state=42)

#Instanciar randomforest
rf_model = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42)

#Escalonando os dados
scaler = MinMaxScaler()
input_train_scaled = scaler.fit_transform(input_train)

input_test_scaled = scaler.transform(input_test)

#Treinando o Algoritimo
rf_model.fit(input_train_scaled, output_train)

rf_predict = rf_model.predict(input_test_scaled)

print("Acurácia:", accuracy_score(output_test, rf_predict))
print("Matriz de confusão:\n", confusion_matrix(output_test, rf_predict))
print("Relatório de classificação:\n", classification_report(output_test, rf_predict))

Acurácia: 0.13725490196078433
Matriz de confusão:
 [[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
Relatório de classificação:
               precision    recall  f1-score   support

         5.0       0.00      0.00      0.00         1
         7.0       0.33      0.50      0.40         2
         8.0       0.00      0.00      0.00         0
         9.0       0.00      0.00      0.00         0
        10.0       0.00      0.00      0.00         4
        11.0       0.00      0.00      0.00         2
        12.0       0.00      0.00      0.00         0
        13.0       0.12      0.25      0.17         4
        14.0       0.00      0.00      0.00         5
        15.0       0.00      0.00      0.00         4
        16.0       0.00      0.00      0.00         2
        17.0       0.00      0.00      0.00         6
        18.0       0.12      0.17      0.14         6
        19.0       0.14      0.17      0.15         6
        20.0       0.40      0.18      0.25        11
        21.0       0.17      0.12      0.14         8
        22.0       0.09      0.25      0.13         4
        23.0       0.10      0.17      0.12         6
        24.0       0.33      0.12      0.18         8
        25.0       0.20      0.20      0.20         5
        26.0       0.00      0.00      0.00         1
        28.0       0.00      0.00      0.00         3
        29.0       0.00      0.00      0.00         2
        30.0       0.00      0.00      0.00         1
        31.0       0.00      0.00      0.00         1
        32.0       0.00      0.00      0.00         2
        33.0       0.00      0.00      0.00         0
        35.0       0.40      0.67      0.50         3
        37.0       0.00      0.00      0.00         0
        44.0       0.00      0.00      0.00         1
        47.0       0.00      0.00      0.00         0
        48.0       0.00      0.00      0.00         1
        50.0       1.00      0.33      0.50         3

    accuracy                           0.14       102
   macro avg       0.10      0.09      0.09       102
weighted avg       0.17      0.14      0.14       102

c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aSHUA\OneDrive\Desktop\Boston-Housing-main\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])